name: Publish package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build and publish classnames-minifier
        run: |
          cd packages/classnames-minifier
          pnpm run build
          cp ../../LICENSE .
          [ ! -f README.md ] && cp ../../README.md .
          npm set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
          npm version --no-git-tag-version ${{github.ref_name}}
          if [[ "${{github.ref_name}}" == *"canary"* ]]; then
            npm publish --tag canary --access public
          else
            npm publish --access public
          fi

      - name: Wait for npm registry propagation
        run: sleep 3

      - name: Install latest classnames-minifier in other packages
        run: |
          for package in packages/*/; do
            if [ "$(basename "$package")" != "classnames-minifier" ]; then
              echo "Installing classnames-minifier@${{github.ref_name}} in $package"
              cd "$package"
              pnpm add classnames-minifier@${{github.ref_name}}
              cd - > /dev/null
            fi
          done

      - name: Build and publish other packages
        run: |
          npm set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
          for package in packages/*/; do
            if [ "$(basename "$package")" != "classnames-minifier" ]; then
              echo "Building and publishing package: $package"
              cd "$package"
              pnpm run build
              cp ../../LICENSE .
              [ ! -f README.md ] && cp ../../README.md .
              npm version --no-git-tag-version ${{github.ref_name}}
              if [[ "${{github.ref_name}}" == *"canary"* ]]; then
                npm publish --tag canary --access public
              else
                npm publish --access public
              fi
              cd - > /dev/null
            fi
          done
